class helper {
  static String? Country;
  static List<String> countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini (fmr. Swaziland)',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (formerly Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Abkhazia',
    'Akrotiri and Dhekelia',
    'American Samoa',
    'Anguilla',
    'Aruba',
    'Bermuda',
    'Bouvet Island',
    'British Indian Ocean Territory',
    'British Virgin Islands',
    'Cayman Islands',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Cook Islands',
    'Curaçao',
    'Falkland Islands',
    'Faroe Islands',
    'French Guiana',
    'French Polynesia',
    'French Southern and Antarctic Lands',
    'Gibraltar',
    'Greenland',
    'Guadeloupe',
    'Guam',
    'Guernsey',
    'Heard Island and McDonald Islands',
    'Hong Kong',
    'Isle of Man',
    'Jersey',
    'Macau',
    'Martinique',
    'Mayotte',
    'Montserrat',
    'New Caledonia',
    'Niue',
    'Norfolk Island',
    'Pitcairn Islands',
    'Puerto Rico',
    'Réunion',
    'Saint Barthelemy',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'London',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Saint Helena',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'Sint Maarten',
    'South Georgia and the South Sandwich Islands',
    'Tokelau',
    'Turks and Caicos Islands',
    'U.S. Virgin Islands',
    'Wallis and Futuna',
    'Western Sahara',
    'Western Samoa',
    'Kosovo',
    'Northern Cyprus',
    'Palestine',
    'Sahrawi Arab Democratic Republic',
    'Somaliland',
    'Taiwan',
    'Transnistria',
    'Turkish Republic of Northern Cyprus',
    'Vatican City',
    'Nagorno-Karabakh',
    'Vatican City State',
    'Western Sahara',
    'Azores',
    'Madeira',
    'Macaronesia',
    'Cabo Verde',
    'Réunion',
    'Bermuda',
    'Azores',
    'Comoros',
    'Ethiopia',
    'Eritrea',
    'Andorra',
    'Ecuador',
    'Finland',
    'Iceland',
    'Jamaica',
    'Kiribati',
    'Lesotho',
    'Malaysia',
    'Monaco',
    'Mongolia',
    'Swaziland',
    'Papua New Guinea',
    'Paraguay',
  ];
}
